name: vpool
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.11
  uuid: ^4.4.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_database: ^10.5.7 
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  firebase_storage: any
  image_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    -  assets/profile.png
