// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNzoa6ILWadQl24OcF4HMw6gqRn8m7NOY',
    appId: '1:785538152739:web:860a5d0365e660b5bf7496',
    messagingSenderId: '785538152739',
    projectId: 'vpool-c8fdb',
    authDomain: 'vpool-c8fdb.firebaseapp.com',
    databaseURL: 'https://vpool-c8fdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vpool-c8fdb.firebasestorage.app',
    measurementId: 'G-Z4DZN1CZHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrSbTds4G-ySZTU7f2czGFUsTMSZEjYX4',
    appId: '1:785538152739:android:1c1df3df5be1b55bbf7496',
    messagingSenderId: '785538152739',
    projectId: 'vpool-c8fdb',
    databaseURL: 'https://vpool-c8fdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vpool-c8fdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB47HO_q01qY5ryo70mN3K2q28LzbVDE3o',
    appId: '1:785538152739:ios:6e4c99ec0aaeb124bf7496',
    messagingSenderId: '785538152739',
    projectId: 'vpool-c8fdb',
    databaseURL: 'https://vpool-c8fdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vpool-c8fdb.firebasestorage.app',
    iosBundleId: 'com.example.vpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB47HO_q01qY5ryo70mN3K2q28LzbVDE3o',
    appId: '1:785538152739:ios:6e4c99ec0aaeb124bf7496',
    messagingSenderId: '785538152739',
    projectId: 'vpool-c8fdb',
    databaseURL: 'https://vpool-c8fdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vpool-c8fdb.firebasestorage.app',
    iosBundleId: 'com.example.vpool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNzoa6ILWadQl24OcF4HMw6gqRn8m7NOY',
    appId: '1:785538152739:web:6789f161ed744adebf7496',
    messagingSenderId: '785538152739',
    projectId: 'vpool-c8fdb',
    authDomain: 'vpool-c8fdb.firebaseapp.com',
    databaseURL: 'https://vpool-c8fdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vpool-c8fdb.firebasestorage.app',
    measurementId: 'G-8TJJMB0KX3',
  );
}
